### PR TITLE
Move to JS based crawler.

### PR DESCRIPTION
**Pull request by RoySegall**
The crawler can get the urls of the files and will output the next json:
```python
                object = {
                    'url':'http://ab.com',
                    'fund_body': 'amitim',
                    'scrapped_date': 156487689,
                    'quarter': 01,
                    'year': 17,
                }
```

What working:
amitim, yl-invest, as-invest, clalbit

### CODE REVIEW

**Comment by RoySegall** [comment]
@nirgn975 We have the fnx.

**Comment by RoySegall** [comment]
@nirgn975 I managed to pull xnes xsl files, partly.

We now need to handle `meitav_dash`, `harel` and `menora`

**Comment by nirgn975** [comment]
@RoySegall What do you mean by "partly"? Which ones can't you pull?

**Comment by RoySegall** [comment]
Because the fu***king xnes have variours names with the xsl files - they don't have any format.

Told that to Moshe.

**Comment by nirgn975** [comment]
F them! okay..

**Comment by RoySegall** [comment]
https://youtu.be/yiPbxvHp6ng?t=20s

**Pull request merged**
